-- H2 2.2.224;
;             
CREATE USER IF NOT EXISTS "SA" SALT 'a6977be0f1dd50da' HASH 'ccd7adabf61edf798773ba84b95e7185d88bec01ef8086dfd28032a02eb51cad' ADMIN;         
CREATE CACHED TABLE "PUBLIC"."COLLABORATION_REQUEST"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 79) NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "IDEA_ID" BIGINT,
    "MESSAGE" CHARACTER VARYING(255),
    "REQUESTER_NAME" CHARACTER VARYING(255),
    "STATUS" CHARACTER VARYING(255),
    "REQUESTER_EMAIL" CHARACTER VARYING(255),
    "REQUESTER_SKILLS" CHARACTER VARYING(255)
);           
ALTER TABLE "PUBLIC"."COLLABORATION_REQUEST" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("ID");        
-- 25 +/- SELECT COUNT(*) FROM PUBLIC.COLLABORATION_REQUEST;  
INSERT INTO "PUBLIC"."COLLABORATION_REQUEST" VALUES
(23, NULL, 1, 'I''d like to collaborate on this idea.', 'Guest User', 'ACCEPTED', 'guest@ideaforge.com', 'React, Java'),
(24, NULL, 3, 'I''d like to collaborate on this idea.', 'Guest User', 'REJECTED', 'guest@ideaforge.com', 'React, Java'),
(25, NULL, 4, 'I''d like to collaborate on this idea.', 'Guest User', 'REJECTED', 'guest@ideaforge.com', 'React, Java'),
(26, NULL, 5, 'I''d like to collaborate on this idea.', 'Guest User', 'ACCEPTED', 'guest@ideaforge.com', 'React, Java'),
(27, NULL, 1, 'I''d like to collaborate on this idea.', 'Rohit', 'ACCEPTED', 'guest@ideaforge.com', 'React, Java'),
(28, NULL, 1, 'I''d like to collaborate on this idea.', 'yeruva ashmitha', 'ACCEPTED', 'user@email.com', 'React, Java'),
(29, NULL, 5, 'I''d like to collaborate on this idea.', 'yeruva ashmitha', 'ACCEPTED', 'user@email.com', 'React, Java'),
(30, NULL, 4, 'I''d like to collaborate on this idea.', 'yeruva ashmitha', 'ACCEPTED', 'user@email.com', 'React, Java'),
(31, NULL, 1, 'I''d like to collaborate on this idea.', 'Bhavana', 'ACCEPTED', 'user@email.com', 'React, Java'),
(32, NULL, 6, 'I''d like to collaborate on this idea.', 'Bhavana', 'ACCEPTED', 'user@email.com', 'React, Java'),
(33, NULL, 6, 'I''d like to collaborate on this idea.', 'yeruva ashmitha', 'ACCEPTED', 'user@email.com', 'React, Java'),
(34, NULL, 4, 'I''d like to collaborate on this idea.', 'Nishii', 'ACCEPTED', 'user@email.com', 'React, Java'),
(35, NULL, 1, 'I''d like to collaborate on this idea.', 'Nishii', 'ACCEPTED', 'user@email.com', 'React, Java'),
(36, NULL, 3, 'I''d like to collaborate on this idea.', NULL, 'ACCEPTED', 'nishi@gmail.com', 'coding, full stack, sql'),
(37, NULL, 1, 'I''d like to collaborate on this idea.', NULL, 'ACCEPTED', 'nishi@gmail.com', 'coding, full stack, sql'),
(38, NULL, 7, 'I''d like to collaborate on this idea.', 'yeruva ashmitha', 'ACCEPTED', '', ''),
(39, NULL, 5, 'I''d like to collaborate on this idea.', NULL, 'ACCEPTED', '', ''),
(40, NULL, 8, 'Hi Guest User, I''d like to collaborate with you on this idea.', 'Shreedha', 'ACCEPTED', 'shree@gmail.com', 'c, sql, mern stack'),
(41, TIMESTAMP '2026-03-16 22:03:27.578511', 1, 'I''d like to collaborate on this idea.', 'Stellin Mary', 'ACCEPTED', 'stellin@gmail.com', 'sql, python,AI/ML'),
(42, TIMESTAMP '2026-03-16 22:14:21.030578', 4, 'Hi Rahul, I''d like to collaborate with you on this idea.', 'yeruva ashmitha', 'REJECTED', 'ashmithareddy2005@gmail.com', 'java full stack, MERN, Sql, python'),
(43, TIMESTAMP '2026-03-23 20:38:34.812584', 1, 'I''d like to collaborate on this idea.', 'yeruva ashmitha', 'REJECTED', 'ashmithareddy2005@gmail.com', 'java full stack, MERN, Sql, python'),
(44, TIMESTAMP '2026-04-02 09:30:05.423001', 7, 'I''d like to collaborate on this idea.', 'Sanjana', 'PENDING', 'sanju@gmail.com', 'MERN , java, sql'),
(76, TIMESTAMP '2026-04-02 11:15:27.330808', 6, 'I''d like to collaborate on this idea.', 'yeruva ashmitha', 'PENDING', 'ashmithareddy2005@gmail.com', 'java full stack, MERN, Sql, python'),
(77, TIMESTAMP '2026-04-02 11:21:03.363459', 9, 'I''d like to collaborate on this idea.', 'yeruva ashmitha', 'PENDING', 'ashmithareddy2005@gmail.com', 'java full stack, MERN, Sql, python'),
(78, TIMESTAMP '2026-04-02 11:41:41.664353', 6, 'Hi Rohit, I''d like to collaborate with you on this idea.', 'Sanjana', 'PENDING', 'sanju@gmail.com', 'MERN , java, sql');            
CREATE CACHED TABLE "PUBLIC"."COMMENT"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 14) NOT NULL,
    "COMMENT_TEXT" CHARACTER VARYING(1000),
    "CREATED_AT" TIMESTAMP(6),
    "IDEA_ID" BIGINT,
    "USERNAME" CHARACTER VARYING(255)
);              
ALTER TABLE "PUBLIC"."COMMENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("ID");      
-- 13 +/- SELECT COUNT(*) FROM PUBLIC.COMMENT;
INSERT INTO "PUBLIC"."COMMENT" VALUES
(1, NULL, TIMESTAMP '2026-03-11 21:13:12.08948', 1, NULL),
(2, NULL, TIMESTAMP '2026-03-11 21:29:37.075426', 3, NULL),
(3, NULL, TIMESTAMP '2026-03-11 21:35:27.372263', 3, 'Guest User'),
(4, NULL, TIMESTAMP '2026-03-11 21:43:15.6095', 1, 'Guest User'),
(5, NULL, TIMESTAMP '2026-03-11 21:50:31.571826', 3, 'Guest User'),
(6, 'DFGHJK', TIMESTAMP '2026-03-11 22:05:07.371869', 3, 'Guest User'),
(7, 'Wanna collab!', TIMESTAMP '2026-03-12 21:42:51.087396', 4, 'Guest User'),
(8, 'Great idea!', TIMESTAMP '2026-03-13 14:22:59.131428', 5, 'Guest User'),
(9, NULL, TIMESTAMP '2026-03-13 15:30:21.682135', NULL, 'Rohit'),
(10, NULL, TIMESTAMP '2026-03-13 15:32:33.708984', 1, 'Rohit'),
(11, 'Great idea!', TIMESTAMP '2026-03-13 15:40:08.920139', 1, 'Rohit'),
(12, U&'i want to collaborate with the people who are interested\000a', TIMESTAMP '2026-03-14 01:12:33.023584', 6, 'Bhavana'),
(13, 'wanna collab!', TIMESTAMP '2026-03-16 22:03:44.279562', 1, 'Stellin Mary');           
CREATE CACHED TABLE "PUBLIC"."IDEA_CONTRIBUTORS"(
    "IDEA_ID" BIGINT NOT NULL,
    "CONTRIBUTORS" CHARACTER VARYING(255)
);              
-- 16 +/- SELECT COUNT(*) FROM PUBLIC.IDEA_CONTRIBUTORS;      
INSERT INTO "PUBLIC"."IDEA_CONTRIBUTORS" VALUES
(6, 'Bhavana'),
(6, 'yeruva ashmitha'),
(4, 'Guest User'),
(4, 'yeruva ashmitha'),
(4, 'Nishii'),
(3, 'Guest User'),
(7, 'yeruva ashmitha'),
(5, 'Guest User'),
(5, 'yeruva ashmitha'),
(8, 'Shreedha'),
(1, 'Guest User'),
(1, 'Rohit'),
(1, 'yeruva ashmitha'),
(1, 'Bhavana'),
(1, 'Nishii'),
(1, 'Stellin Mary');         
CREATE CACHED TABLE "PUBLIC"."USERS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 50) NOT NULL,
    "EMAIL" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "PASSWORD" CHARACTER VARYING(255),
    "REPUTATION" INTEGER NOT NULL,
    "SKILLS" CHARACTER VARYING(255)
); 
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");        
-- 18 +/- SELECT COUNT(*) FROM PUBLIC.USERS;  
INSERT INTO "PUBLIC"."USERS" VALUES
(1, 'guest@test.com', 'Guest User', '123', 5, 'Java,React'),
(2, 'rahul@gmail.com', 'Rahul', '123', 0, 'React'),
(3, 'ananya@gmail.com', 'Ananya', '123', 0, 'Machine Learning'),
(4, 'rohit@gmail.com', 'Rohit', '123', 0, 'Spring Boot'),
(5, 'ashmithareddy2005@gmail.com', 'yeruva ashmitha', '$2a$10$ZI5Dh4oS7HsAe3Z2GUhl7O6VPcFodWZWT/5JHQrZikripC8iSbsI2', 0, 'java full stack, MERN, Sql, python'),
(6, '23eg105d51@anurag.edu.in', 'srimanya', '$2a$10$Wv70vmrpf7Ndj4fIlPF78uSkINSkX5Anm5E2xRsPASg9xvSx5vnE.', 0, 'java'),
(7, 'bhavana@gmail.com', 'Bhavana', '$2a$10$A8efqNPCTuCTSGkIFxrZI.UwEbFL5hQqSRcjWDKFQrNKMC4.sOwO.', 5, 'Java'),
(8, 'nishi@gmail.com', 'Nishii', '$2a$10$jTyYQJtozq5XYhr9ko8xwu3OLbJJPxKezLmOLUbQisC.lpovzIEBS', 0, 'coding, full stack, sql'),
(9, 'anjali@gamil.com', 'Anjali', '$2a$10$NI1zDLsdkH8Q41MCHJMczue9dQj2jccjz9EI1syJ87hAqCx5f5LJq', 0, 'python, java, sql, dsa'),
(10, 'dhruva@gmail.com', 'dhruva', '$2a$10$rdw/H58AjqpWju.fkOR2AucBjc0mZG5854RD9EEMKmaaic1MlWOum', 0, 'java, full stack, c, sql'),
(11, 'dhruva@gmail.com', 'dhruva', '$2a$10$Q/lue6RCFiYRRZktlMOOouFzaE0cAZF/BVDZkB78JcqKea95io5lK', 0, 'java, full stack, c, sql'),
(12, 'dchittipolu@gmail.com', 'dharshini', '$2a$10$ELCfqcD8FwZmpNsK/JojAes6snKGfdBam0Dkk/D5N2nVzevaV5492', 0, 'c '),
(13, 'pradeepthi@gmail.com', 'pradeepthi', '$2a$10$3JaQDbgsdkuajrFxOsrlNeoCZKmJwoilFbcTlOnZChgoASoMIK4uS', 0, 'java full stack, MERN, Sql, python, java'),
(14, 'test@gmail.com', 'test', '$2a$10$PELA1B1KaJx0LQefr6NzmuYE3b3eKlTuhT5nNbPDAM981i1E18zba', 0, 'java'),
(15, 'lahari@gmail.com', 'Lahari', '$2a$10$aihPruREtGfmtxkuK39xEuHd3hhhn4UCve6OfXLW2e6wn6owvZbj.', 0, 'java full stack'),
(16, 'shree@gmail.com', 'Shreedha', '$2a$10$CMjI.scYB3b/U1AuVg2Z5eACyxwhsY0yHYvq1YLwBcR87r7aNzFj.', 0, 'c, sql, mern stack'),
(17, 'stellin@gmail.com', 'Stellin Mary', '$2a$10$.YkvvChhobaTuFhm/NKur.xFvH61wnVvTXiuYf58aYRi.QEvbGcIW', 0, 'sql, python,AI/ML'),
(18, 'sanju@gmail.com', 'Sanjana', '$2a$10$ko8ZpSuQTIXcflHPDPZ3kO83oc.aHxUdW99XhdF2bJm4kayrOyGI.', 5, 'MERN , java, sql');              
CREATE CACHED TABLE "PUBLIC"."VOTE"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 52) NOT NULL,
    "IDEA_ID" BIGINT,
    "USERNAME" CHARACTER VARYING(255)
);              
ALTER TABLE "PUBLIC"."VOTE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_28" PRIMARY KEY("ID");        
-- 17 +/- SELECT COUNT(*) FROM PUBLIC.VOTE;   
INSERT INTO "PUBLIC"."VOTE" VALUES
(1, 1, 'Guest User'),
(3, 3, 'Guest User'),
(4, 4, 'Guest User'),
(5, 5, 'Guest User'),
(6, 1, 'Rohit'),
(7, 1, 'yeruva ashmitha'),
(8, 4, 'yeruva ashmitha'),
(9, 5, 'yeruva ashmitha'),
(12, 6, 'Bhavana'),
(13, 6, 'yeruva ashmitha'),
(14, 4, 'Nishii'),
(15, 3, NULL),
(16, 7, 'yeruva ashmitha'),
(17, 8, NULL),
(18, 1, 'Stellin Mary'),
(19, 7, 'Sanjana'),
(51, 9, 'yeruva ashmitha');           
CREATE CACHED TABLE "PUBLIC"."NOTIFICATION"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 49) NOT NULL,
    "MESSAGE" CHARACTER VARYING(255),
    "READ_STATUS" BOOLEAN NOT NULL,
    "USERNAME" CHARACTER VARYING(255)
); 
ALTER TABLE "PUBLIC"."NOTIFICATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("ID"); 
-- 32 +/- SELECT COUNT(*) FROM PUBLIC.NOTIFICATION;           
INSERT INTO "PUBLIC"."NOTIFICATION" VALUES
(14, 'Your collaboration request was accepted', FALSE, 'Guest User'),
(15, 'Your collaboration request was rejected', FALSE, 'Guest User'),
(16, 'Your collaboration request was REJECTED for idea ID 4', FALSE, 'Guest User'),
(17, 'Your collaboration request was ACCEPTED for idea ID 5', FALSE, 'Guest User'),
(18, 'New comment added on idea 5', FALSE, 'Guest User'),
(19, 'Rohit commented on your idea: AI POWERED RESUME CHECKER', FALSE, NULL),
(20, 'Rohit commented on your idea: AI POWERED RESUME CHECKER', FALSE, NULL),
(21, 'Rohit requested collaboration on your idea: AI POWERED RESUME CHECKER', FALSE, NULL),
(22, 'Your collaboration request was ACCEPTED for idea: AI POWERED RESUME CHECKER', FALSE, 'Rohit'),
(23, 'yeruva ashmitha requested collaboration on your idea: AI POWERED RESUME CHECKER', FALSE, NULL),
(24, 'Your collaboration request was ACCEPTED for idea: AI POWERED RESUME CHECKER', FALSE, 'yeruva ashmitha'),
(25, 'yeruva ashmitha requested collaboration on your idea: AI Startup Mentor', FALSE, 'Guest User'),
(26, 'yeruva ashmitha requested collaboration on your idea: Smart Waste Management System', FALSE, 'Guest User'),
(27, 'Your collaboration request was ACCEPTED for idea: AI Startup Mentor', FALSE, 'yeruva ashmitha'),
(29, 'Bhavana requested collaboration on your idea: AI POWERED RESUME CHECKER', FALSE, NULL),
(30, 'Bhavana commented on your idea: AI Personal Finance Advisor', FALSE, 'Bhavana'),
(31, 'Bhavana requested collaboration on your idea: AI Personal Finance Advisor', FALSE, 'Bhavana'),
(32, 'yeruva ashmitha requested collaboration on your idea: AI Personal Finance Advisor', FALSE, 'Bhavana'),
(33, 'Your collaboration request was ACCEPTED for idea: AI POWERED RESUME CHECKER', FALSE, 'Bhavana'),
(34, 'Nishii requested collaboration on your idea: Smart Waste Management System', FALSE, 'Guest User'),
(35, 'Nishii requested collaboration on your idea: AI POWERED RESUME CHECKER', FALSE, NULL),
(36, 'Your collaboration request was ACCEPTED for idea: AI Personal Finance Advisor', FALSE, 'Bhavana'),
(37, 'null requested collaboration on your idea: AI career Mentor', FALSE, NULL),
(39, 'null requested collaboration on your idea: AI POWERED RESUME CHECKER', FALSE, NULL),
(40, 'Your collaboration request was ACCEPTED for idea: Smart Waste Management System', FALSE, 'Nishii'),
(41, 'Your collaboration request was ACCEPTED for idea: AI POWERED RESUME CHECKER', FALSE, 'Nishii'),
(42, 'Your collaboration request was ACCEPTED for idea: AI career Mentor', FALSE, NULL),
(43, 'Your collaboration request was ACCEPTED for idea: AI POWERED RESUME CHECKER', FALSE, NULL),
(44, 'yeruva ashmitha requested collaboration on your idea: TraceGraph-AI', FALSE, 'dhruva@gamil.com'),
(46, 'null requested collaboration on your idea: AI Startup Mentor', FALSE, 'Guest User'),
(47, 'Shreedha requested collaboration on your idea: AI Study Planner', FALSE, 'test'),
(48, 'Stellin Mary commented on your idea: AI POWERED RESUME CHECKER', FALSE, NULL);
CREATE CACHED TABLE "PUBLIC"."IDEA"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 10) NOT NULL,
    "CATEGORY" CHARACTER VARYING(255),
    "CREATED_AT" TIMESTAMP(6),
    "PROBLEM_STATEMENT" CHARACTER VARYING(2000),
    "SOLUTION" CHARACTER VARYING(2000),
    "TARGET_AUDIENCE" CHARACTER VARYING(255),
    "TECHNOLOGY_STACK" CHARACTER VARYING(255),
    "TITLE" CHARACTER VARYING(255),
    "VIEWS" INTEGER NOT NULL,
    "VOTES" INTEGER NOT NULL,
    "AUTHOR_NAME" CHARACTER VARYING(255),
    "PROPOSED_SOLUTION" CHARACTER VARYING(2000)
);           
ALTER TABLE "PUBLIC"."IDEA" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");         
-- 8 +/- SELECT COUNT(*) FROM PUBLIC.IDEA;    
INSERT INTO "PUBLIC"."IDEA" VALUES
(1, 'AI', TIMESTAMP '2026-03-11 15:24:47.25257', 'CHECK OUR RESUME ', NULL, 'Students and job seekers', NULL, 'AI POWERED RESUME CHECKER', 151, 10, NULL, NULL),
(3, 'AI', TIMESTAMP '2026-03-11 21:21:46.810206', 'Students don''t know which career suits them.', NULL, 'College, students', 'AI analyzes skills and suggests career paths.', 'AI career Mentor', 75, 2, NULL, NULL),
(4, 'SMART CITY', TIMESTAMP '2026-03-12 21:42:20.51395', 'Cities struggle with inefficient garbage collection leading to overflowing bins and poor sanitation.', NULL, 'Municipal Corporations, Smart Cities', 'IoT Sensors, React, Spring Boot, GPS APIs', 'Smart Waste Management System', 37, 3, 'Guest User', 'Install IoT sensors in bins that detect fill levels and notify waste collectors using a centralized dashboard with optimized routes.'),
(5, 'AI', TIMESTAMP '2026-03-13 14:21:29.717968', 'Students don''t know how to build startups', NULL, 'students', 'MERN Stack , APIs', 'AI Startup Mentor', 22, 2, 'Guest User', 'AI suggests startup ideas and mentors'),
(6, 'FINTECH', TIMESTAMP '2026-03-14 01:10:58.980313', 'Many people struggle to manage their personal finances effectively. They often overspend, fail to save regularly, and lack insights into where their money goes. Traditional budgeting apps require manual input and do not provide intelligent recommendations.', NULL, 'Young professionals  College students  Families managing household budgets  Individuals starting their financial journey', 'React, Spring Boot, MySQL, Open Banking APIs, AI/ML models for financial insights', 'AI Personal Finance Advisor', 22, 2, 'Bhavana', 'Develop an AI-powered personal finance assistant that automatically tracks expenses, categorizes spending, and provides personalized financial advice. The system can analyze spending patterns and suggest ways to save money, optimize investments, and manage monthly budgets.'),
(7, 'AI', TIMESTAMP '2026-03-14 14:29:19.954489', 'A platform where microservices and dependencies are tested and managed.', NULL, 'Developers,Engineers', 'react,springboot,groq', 'TraceGraph-AI', 12, 2, 'dhruva@gamil.com', 'a ai powered tool where data is in the form of json formats and output is ai ready explanation'),
(8, 'AI', TIMESTAMP '2026-03-15 20:20:57.344371', 'Students struggle to manage study schedules', NULL, 'Students', 'React,Spring Boot,AI', 'AI Study Planner', 6, 1, 'test', 'AI tool that generates study plans'),
(9, 'AI', TIMESTAMP '2026-04-02 11:20:27.609166', 'Students today face high levels of stress, anxiety, and burnout due to academic pressure, social expectations, and excessive screen time. However, most mental health solutions are either expensive, not personalized, or not engaging enough for daily use.', NULL, U&'Students, early professionals, and remote workers aged 16\201330', 'React, Node.js, MongoDB, TensorFlow Lite, Web Speech API, OpenAI API, IoT integrations', U&'MindSync \2013 AI-Powered Mental Health Companion for Students', 4, 1, 'Sanjana', U&'MindSync is an AI-powered mental wellness platform that monitors user behavior (screen time, typing speed, activity patterns) and detects early signs of stress. It provides real-time interventions like:\000a\000aPersonalized break suggestions\000aAI-generated calming exercises (breathing, journaling prompts)\000aMood tracking using simple check-ins\000aVoice-based emotional support chatbot\000aIntegration with ambient devices (lights/music) for relaxation\000a\000aThe system uses lightweight AI models to ensure privacy and real-time responsiveness.');       
CREATE CACHED TABLE "PUBLIC"."TEAM_MEMBER"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 8) NOT NULL,
    "IDEA_ID" BIGINT,
    "JOINED_AT" TIMESTAMP(6),
    "ROLE" CHARACTER VARYING(255),
    "USERNAME" CHARACTER VARYING(255)
);     
ALTER TABLE "PUBLIC"."TEAM_MEMBER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("ID");  
-- 7 +/- SELECT COUNT(*) FROM PUBLIC.TEAM_MEMBER;             
INSERT INTO "PUBLIC"."TEAM_MEMBER" VALUES
(1, 6, TIMESTAMP '2026-03-14 10:33:34.330612', 'Collaborator', 'Bhavana'),
(2, 6, TIMESTAMP '2026-03-14 11:13:09.472571', 'Collaborator', 'yeruva ashmitha'),
(3, 4, TIMESTAMP '2026-03-14 12:18:46.958806', 'Collaborator', 'Nishii'),
(4, 1, TIMESTAMP '2026-03-14 12:18:49.975103', 'Collaborator', 'Nishii'),
(5, 3, TIMESTAMP '2026-03-14 12:18:51.323815', 'Collaborator', NULL),
(6, 1, TIMESTAMP '2026-03-14 12:18:52.510089', 'Collaborator', NULL),
(7, 7, TIMESTAMP '2026-03-14 14:41:00.645699', 'Collaborator', 'yeruva ashmitha');             
CREATE CACHED TABLE "PUBLIC"."ACTIVITY"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 74) NOT NULL,
    "ACTION" CHARACTER VARYING(255),
    "CREATED_AT" TIMESTAMP(6),
    "IDEA_TITLE" CHARACTER VARYING(255),
    "USERNAME" CHARACTER VARYING(255),
    "TARGET" CHARACTER VARYING(255)
);           
ALTER TABLE "PUBLIC"."ACTIVITY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("ID");     
-- 42 +/- SELECT COUNT(*) FROM PUBLIC.ACTIVITY;               
INSERT INTO "PUBLIC"."ACTIVITY" VALUES
(1, 'submitted idea', TIMESTAMP '2026-03-13 14:21:29.801098', 'AI Startup Mentor', 'Guest User', NULL),
(2, 'upvoted', TIMESTAMP '2026-03-13 14:21:38.903954', 'Idea 5', 'Guest User', NULL),
(3, 'joined idea', TIMESTAMP '2026-03-13 14:21:56.385502', 'AI Startup Mentor', 'Guest User', NULL),
(4, 'commented on', TIMESTAMP '2026-03-13 14:22:59.134432', 'Idea 5', 'Guest User', NULL),
(5, 'upvoted', TIMESTAMP '2026-03-13 15:29:54.932709', NULL, 'Rohit', 'Idea 1'),
(6, 'upvoted', TIMESTAMP '2026-03-13 15:29:55.026354', NULL, 'Rohit', 'Idea 1'),
(7, 'commented on', TIMESTAMP '2026-03-13 15:30:21.686132', NULL, 'Rohit', 'Idea null'),
(8, 'commented on', TIMESTAMP '2026-03-13 15:32:33.727971', NULL, 'Rohit', 'Idea 1'),
(9, 'commented on', TIMESTAMP '2026-03-13 15:40:08.928141', NULL, 'Rohit', 'Idea 1'),
(10, 'joined idea', TIMESTAMP '2026-03-13 16:00:48.618833', NULL, 'Rohit', 'AI POWERED RESUME CHECKER'),
(11, 'upvoted', TIMESTAMP '2026-03-13 21:34:37.337141', NULL, 'yeruva ashmitha', 'Idea 1'),
(12, 'upvoted', TIMESTAMP '2026-03-13 22:06:18.773302', NULL, 'yeruva ashmitha', 'Idea 4'),
(13, 'joined idea', TIMESTAMP '2026-03-13 22:09:07.799835', NULL, 'yeruva ashmitha', 'AI POWERED RESUME CHECKER'),
(14, 'upvoted', TIMESTAMP '2026-03-13 23:41:10.978051', NULL, 'yeruva ashmitha', 'Idea 5'),
(15, 'joined idea', TIMESTAMP '2026-03-14 01:01:48.468258', NULL, 'yeruva ashmitha', 'AI Startup Mentor'),
(16, 'joined idea', TIMESTAMP '2026-03-14 01:01:50.212201', NULL, 'yeruva ashmitha', 'Smart Waste Management System'),
(17, 'upvoted', TIMESTAMP '2026-03-14 01:03:14.588944', NULL, 'Bhavana', 'Idea 1'),
(18, 'removed vote from', TIMESTAMP '2026-03-14 01:03:37.505668', NULL, 'Bhavana', 'Idea 1'),
(19, 'submitted idea', TIMESTAMP '2026-03-14 01:10:59.019113', NULL, 'Bhavana', 'AI Personal Finance Advisor'),
(20, 'commented on', TIMESTAMP '2026-03-14 01:12:33.039336', NULL, 'Bhavana', 'Idea 6'),
(21, 'upvoted', TIMESTAMP '2026-03-14 01:13:03.155287', NULL, 'Bhavana', 'Idea 6'),
(22, 'removed vote from', TIMESTAMP '2026-03-14 01:13:05.595329', NULL, 'Bhavana', 'Idea 6'),
(23, 'upvoted', TIMESTAMP '2026-03-14 01:13:08.155197', NULL, 'Bhavana', 'Idea 6'),
(24, 'upvoted', TIMESTAMP '2026-03-14 01:14:59.060231', NULL, 'yeruva ashmitha', 'Idea 6'),
(25, 'joined idea', TIMESTAMP '2026-03-14 01:15:29.2878', NULL, 'Bhavana', 'AI POWERED RESUME CHECKER'),
(26, 'upvoted', TIMESTAMP '2026-03-14 09:08:38.856704', NULL, 'Nishii', 'Idea 4'),
(27, 'joined idea', TIMESTAMP '2026-03-14 10:33:34.364092', NULL, 'Bhavana', 'AI Personal Finance Advisor'),
(28, 'upvoted', TIMESTAMP '2026-03-14 10:35:50.375734', NULL, NULL, 'Idea 3'),
(29, 'joined idea', TIMESTAMP '2026-03-14 11:13:09.476569', NULL, 'yeruva ashmitha', 'AI Personal Finance Advisor'),
(30, 'joined idea', TIMESTAMP '2026-03-14 12:18:46.968819', NULL, 'Nishii', 'Smart Waste Management System'),
(31, 'joined idea', TIMESTAMP '2026-03-14 12:18:49.97711', NULL, 'Nishii', 'AI POWERED RESUME CHECKER'),
(32, 'joined idea', TIMESTAMP '2026-03-14 12:18:51.326084', NULL, NULL, 'AI career Mentor'),
(33, 'joined idea', TIMESTAMP '2026-03-14 12:18:52.512307', NULL, NULL, 'AI POWERED RESUME CHECKER'),
(34, 'submitted idea', TIMESTAMP '2026-03-14 14:29:20.098849', NULL, 'yeruva ashmitha', 'TraceGraph-AI'),
(35, 'upvoted', TIMESTAMP '2026-03-14 14:40:09.255518', NULL, 'yeruva ashmitha', 'Idea 7'),
(36, 'joined idea', TIMESTAMP '2026-03-14 14:41:00.647078', NULL, 'yeruva ashmitha', 'TraceGraph-AI'),
(37, 'upvoted', TIMESTAMP '2026-03-15 21:24:20.001217', NULL, NULL, 'Idea 8'),
(38, 'upvoted', TIMESTAMP '2026-03-16 22:03:34.320671', NULL, 'Stellin Mary', 'Idea 1'),
(39, 'commented on', TIMESTAMP '2026-03-16 22:03:44.284561', NULL, 'Stellin Mary', 'Idea 1'),
(40, 'upvoted', TIMESTAMP '2026-04-02 09:30:03.95975', NULL, 'Sanjana', 'Idea 7'),
(72, 'submitted idea', TIMESTAMP '2026-04-02 11:20:27.635752', NULL, 'Sanjana', U&'MindSync \2013 AI-Powered Mental Health Companion for Students'),
(73, 'upvoted', TIMESTAMP '2026-04-02 11:20:59.685124', NULL, 'yeruva ashmitha', 'Idea 9');            
ALTER TABLE "PUBLIC"."IDEA_CONTRIBUTORS" ADD CONSTRAINT "PUBLIC"."FKKEVFC9ULVHPDVEA8VWOVMH6UU" FOREIGN KEY("IDEA_ID") REFERENCES "PUBLIC"."IDEA"("ID") NOCHECK;               
